FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Meezan API

Meezan is a simple and free Quran browser application, with integrations with modern
agents. Its goals are to make the glorious Quran available in the emerging world of
ambient computing.

This API powers the Meezan client applications, Progressive Web App, as well as moder
agents.

## Credits

With thanks, Meezan acknowledges and depends on the following resources:

1. Node.js ``quran-promise`` module: https://github.com/axis-tip/quran-promise
2. Tanzil project: http://tanzil.net/
3. EveryAyah: http://everyayah.com/data/status.php

## Chapters (Surahs) Collection [/chapters]

### List All Chapters [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]